<?php /** @var Toptal\Blog\Block\Posts $block */ ?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $block->getActionUrl();?>" data-hasrequired=""
         data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
              <legend><span>Post <?php echo $block->getPost()->getId(); ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span>Title</span></label>
                            <div class="control">
			<input name="id" id="id" value="<?php echo $block->getPost()->getId(); ?>" type="hidden">
                            <input name="title" id="Title" title="Title" value="<?php echo $block->getPost()->getTitle(); ?>" class="input-text" type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="content"><span>Content</span></label>
                            <div class="control">
                                <textarea name="content" id="content" rows="5" cols="8" class="input-text" data-validate="{required:true}"><?php echo $block->getPost()->getContent(); ?></textarea>
                            </div>
                        </div>
                    </div>
            </fieldset>
            </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
            </div>
        </div>
        </form>
	<form name="addD" method="post" id="addD" class="form" action="<?php echo $block->getDeleteUrl();?>">
	<input name="id" id="id" value="<?php echo $block->getPost()->getId(); ?>" type="hidden">
	<button type="submit" style="margin-top: 10px;" onclick="" class="action submit primary" title="Delete"><span>Delete</span></button>
	</form>
	
    </div>
</div>


