<?php /** @var Toptal\Blog\Block\Posts $block */ ?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $block->getActionUrl();?>" data-hasrequired=""
         data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
              <legend><span>Post</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span>Title</span></label>
                            <div class="control">
                            <input name="title" id="Title" title="Title" value="" class="input-text" type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="content"><span>Content</span></label>
                            <div class="control">
                                <textarea name="content" id="content" rows="5" cols="8" class="input-text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </div>
            </fieldset>
            </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
            </div>
        </div>
        </form>
    </div>
</div>


